# Generated by Django 4.1 on 2022-09-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMEINO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_no', models.CharField(max_length=400)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
