# Generated by Django 4.1 on 2022-08-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_customer_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
