# Generated by Django 4.1 on 2022-11-28 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_fixoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixoffer',
            old_name='phonee',
            new_name='imei_no',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='date_valid',
            new_name='date_ending_to',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='precedence',
        ),
        migrations.AddField(
            model_name='offers',
            name='date_starting_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='prize_details',
            field=models.CharField(default='Happy Sales Carnival', max_length=900),
        ),
    ]
