# Generated by Django 4.1 on 2022-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_offers_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
