# Generated by Django 4.1 on 2022-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_alter_gift_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
