# Generated by Django 4.1 on 2022-11-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_rename_phonee_fixoffer_imei_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-date_of_purchase',)},
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='date_ending_to',
            new_name='date_valid',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='precedence',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='date_starting_from',
        ),
    ]
